# Generated by Django 5.1.5 on 2025-02-13 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_order'),
        ('movies', '0004_alter_movie_image'),
    ]

    operations = [
    ]
