# Generated by Django 5.1.5 on 2025-02-13 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_merge_0002_order_0004_alter_movie_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
